const Data = [{
    id:1,
    date: "2025-03-06",
    type: "Project Discussion",
    location:"Hayat Hotel",
    description: "Discuss project timeline and deliverables.",
    time: "10:00 AM",
  },
  {
    id:2,
    date: "2025-03-07",
    type: "Client Meeting",
    location:"Soltie Hotel",
    description: "Meeting with the client to present progress.",
    time: "02:30 PM",
  },
  {
    id:3,
    date: "2025-03-07",
    type: "Client Meeting",
    location:"Kalanki",
    description: "Meeting with the client to present progress.",
    time: "02:30 PM",
  },
  {
    id:1,
    date: "2025-03-06",
    type: "Project Discussion",
    location:"Hayat Hotel",
    description: "Discuss project timeline and deliverables.",
    time: "10:00 AM",
  },
  {
    id:2,
    date: "2025-03-07",
    type: "Client Meeting",
    location:"Soltie Hotel",
    description: "Meeting with the client to present progress.",
    time: "02:30 PM",
  },
  {
    id:1,
    date: "2025-03-06",
    type: "Project Discussion",
    location:"Hayat Hotel",
    description: "Discuss project timeline and deliverables.",
    time: "10:00 AM",
  },
  {
    id:2,
    date: "2025-03-07",
    type: "Client Meeting",
    location:"Soltie Hotel",
    description: "Meeting with the client to present progress.",
    time: "02:30 PM",
  },
  {
    id:1,
    date: "2025-03-06",
    type: "Project Discussion",
    location:"Hayat Hotel",
    description: "Discuss project timeline and deliverables.",
    time: "10:00 AM",
  },
  {
    id:2,
    date: "2025-03-07",
    type: "Client Meeting",
    location:"Soltie Hotel",
    description: "Meeting with the client to present progress.",
    time: "02:30 PM",
  },
  {
    id:1,
    date: "2025-03-06",
    type: "Project Discussion",
    location:"Hayat Hotel",
    description: "Discuss project timeline and deliverables.",
    time: "10:00 AM",
  },
  {
    id:2,
    date: "2025-03-07",
    type: "Client Meeting",
    location:"Soltie Hotel",
    description: "Meeting with the client to present progress.",
    time: "02:30 PM",
  },
  {
    id:1,
    date: "2025-03-06",
    type: "Project Discussion",
    location:"Hayat Hotel",
    description: "Discuss project timeline and deliverables.",
    time: "10:00 AM",
  },
  {
    id:2,
    date: "2025-03-07",
    type: "Client Meeting",
    location:"Soltie Hotel",
    description: "Meeting with the client to present progress.",
    time: "02:30 PM",
  },
];